apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: nginx-deployment
spec:
  replicas: 3
  template:
    template:
      metadata:
        name: nginx-pod
        labels:
          app: nginx-pod
      spec:
        containers:
          - name: nginx-container
            image: nginx:stable
            ports:
              - containerPort: 80
  selector:
    matchLabels:
      app: nginx-pod